<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-19T18:02:46 IST" name="Default suite" finished-at="2025-07-19T18:02:55 IST" duration-ms="8812">
    <groups>
    </groups>
    <test started-at="2025-07-19T18:02:46 IST" name="Default test" finished-at="2025-07-19T18:02:55 IST" duration-ms="8812">
      <class name="tests.UsersTest">
        <test-method is-config="true" signature="preSetup()[pri:0, instance:tests.UsersTest@71d44a3]" started-at="2025-07-19T18:02:46 IST" name="preSetup" finished-at="2025-07-19T18:02:46 IST" duration-ms="21" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSetup -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.UsersTest@71d44a3]" started-at="2025-07-19T18:02:46 IST" name="setUp" finished-at="2025-07-19T18:02:48 IST" duration-ms="1317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyAddUser()[pri:0, instance:tests.UsersTest@71d44a3]" started-at="2025-07-19T18:02:48 IST" name="verifyAddUser" finished-at="2025-07-19T18:02:51 IST" duration-ms="2925" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddUser -->
        <test-method signature="verifyAddUserUsingMap()[pri:0, instance:tests.UsersTest@71d44a3]" started-at="2025-07-19T18:02:51 IST" name="verifyAddUserUsingMap" finished-at="2025-07-19T18:02:52 IST" duration-ms="999" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddUserUsingMap -->
        <test-method signature="verifyEndToEndFlow()[pri:0, instance:tests.UsersTest@71d44a3]" started-at="2025-07-19T18:02:52 IST" name="verifyEndToEndFlow" finished-at="2025-07-19T18:02:54 IST" duration-ms="2278" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at tests.UsersTest.verifyEndToEndFlow(UsersTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyEndToEndFlow -->
        <test-method signature="verifyGetUser()[pri:0, instance:tests.UsersTest@71d44a3]" started-at="2025-07-19T18:02:54 IST" name="verifyGetUser" finished-at="2025-07-19T18:02:54 IST" duration-ms="694" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyGetUser -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:tests.UsersTest@71d44a3]" started-at="2025-07-19T18:02:54 IST" name="cleanUp" finished-at="2025-07-19T18:02:55 IST" duration-ms="530" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- tests.UsersTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
